### ISSUE TITLE
Investigate on how to provide support for build on cluster feature

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-knative#200]
Building a function on cluster is an operation which requires tekton and knative func cli.

The process is quite simple (starting from an empty cluster)
1) install tekton on your cluster
2) install all tekton tasks needed for building a knative func + add permissions to the default service account
3) create a new func
4) initialize a git repo 
5) add the build git section to the `func.yaml` file. Example:
```
build: git                                          # required, specify `git` build type
git:
  url: https://github.com/my-repo/my-function.git   # required, git repository with the function source code
  revision: main                                    # optional, git revision to be used (branch, tag, commit)
  # contextDir: myfunction                          # optional, needed only if the function is not located
                                                    # in the repository root folder
```
6) push everything on git
7) execute the `kn func deploy` command
8) to update your func, push the new code to git and re-run `kn func deploy`

So what kind of support we would like to offer? 
By separating each point I think this. The only aspect I can think of (not sure if and how it can be possible) is the interaction with the tekton plugin if installed.

1) nothing to do
2) nothing? The tekton tasks installation is something that can be done with the tekton plugin. Nothing related to knative.
3) already supported
4) nothing to do
5) we can add a code completion helper when working with it
6) nothing to do
7) already supported
8) nothing to do

Thoughts? WDYT? @mohitsuman @sudhirverma 
Description -> https://github.com/knative-sandbox/kn-plugin-func/blob/044177026725adb6591c7cf4593d59755e34dd0a/docs/reference/on_cluster_build.md
