### ISSUE TITLE
Display sinks node in the tree

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/intellij-knative#39]
A sink can also be created separated by an event source, so a sink node that lists all sinks in the namespace could make sense.
E.g 
```
apiVersion: eventing.knative.dev/v1alpha1
kind: KafkaSink
metadata:
   name: my-kafka-sink
   namespace: default
spec:
   topic: mytopic
   bootstrapServers:
      - my-cluster-kafka-bootstrap.kafka:9092
   auth.secret.ref.name: my_secret
```
